[package]
name = "afmt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.16"
tree-sitter = "0.22.6"

[build-dependencies]
cc = "1.1.10"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
